### ISSUE TITLE
Valid K8s Cluster config name fails in validation

### ISSUE THREAD

**Issue by dmatch01** [sky-shift/skyshift#19]
Valid K8s context example from `./kube/config`:
```
- context:
    cluster: c1-e-us-south-containers-cloud-com:80001
    namespace: default
    user: IAM#darroyo@us.ibm.com/c1-e-us-south-containers-cloud-com:80001
  name: default/c1-e-us-south-containers-cloud-com:80001/IAM#darroyo@us.ibm.com
```
`name` fails SkyFlow regex restrictions [here](https://github.com/michaelzhiluo/skyflow/blob/main/skyflow/templates/object_template.py#L54).

@michaelzhiluo: What is the source of this restriction?  Is it `etcd`?  Any insight would be helpful.
