### ISSUE TITLE
[K8s] Allocatable resources are not properly fetched

### ISSUE THREAD

**Issue by AlexCuadron** [sky-shift/skyshift#265]
Spin up a k8s cluster, then retrieve node resources with `kubectl get node <node_name> -o yaml`:
Example output:
```
  allocatable:
    cpu: 1930m
    ephemeral-storage: "8397760472"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 6176744Ki
    pods: "110"
```
Consequently, SkyShift reports: `cpus: 1.93/1.93 `. However, the **REAL** allocatable resources are:
`1930 - 616 = 1294 vCPU`.
The `616` number was derived from all CPU values requested from all pods running in that node.
